tiny-registry-config:
  wasm-file: ./tiny-registry.wasm
  wasm-function: handle
  http-port: 9090
  log-level: info
  service-name: tiny-registry
  registry-mode: true
  admin-registry-token: morrison-hotel
  registry-path: ./wasm-files
  information: ğŸ‘‹ I'm the registry service ğŸ³

